services:
  nestapp:
    container_name: nestapp
    image: peores-peliculas-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=${DB_TYPE}
      - PG_HOST=db
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_NAME=${PG_NAME}
      - PG_PORT=${PG_PORT}
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

